### ISSUE TITLE
Misplaced `limit` parameter

### ISSUE THREAD

**Issue by ysmolyaninov** [cattle-ops/terraform-aws-gitlab-runner#1005]
I've recently upgraded to the version 7.* and the new parameter grouping really makes it easier to read and understand - thanks for that. 
I find, however variable that lands in [the runner config](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/7.1.0/template/runner-config.tftpl#L20) as limit, which is the maximum number of machines building and idle, being sourced from [a variable under runner_worker](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/7.1.0/main.tf#L121). [Here](https://docs.gitlab.com/runner/configuration/autoscale.html) is the reference to Gitlab documentation.
In addition the variable used has [a misleading description](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/7.1.0/variables.tf#L371) because it's put to the mentioned parameter in the config.

I'd propose to put it under runner_manager as limit to reflect where it lands in the config and to reflect its place in the parameter hierarchy. Or at least change the description, if backwards compatibility is crucial. 

P.S. I could make a PR if this is actually recognized as an issue that requires action.

**Comment by kayman-mk** [comment]
You are right. Better move the variable and correct the description.

PR is highly appreciated. Backwards compatibility is needed, but I will add this to the v8 Release as soon as I have the new variable name. So I suggest to
- introduce the new variable
- mark the old one as deprecated and refer to the new one
- use the value from the old variable or, if missing, use the new one.
