### ISSUE TITLE
remove_gitlab_registration script doesnt run on termination of instance

### ISSUE THREAD

**Issue by robpearce-flux** [cattle-ops/terraform-aws-gitlab-runner#1014]
it seems like the intention is for the /etc/init.d/remove_gitlab_registration script to run on instance termination to runlevel 0. This doesn't seem to be happening. As far as i can tell the script works in itself, and when triggered manually with a stop command it works ok - it just doesn't actually run when a machine is terminated in aws. So when we use terraform to destroy them it's not being run. 

This used to work for us on older versions of the module but stopped working at some point. Needing us to manually remove the runners from the gitlab UI now. I don't know if its due to some chance or timing related difference on AWS's side, though.

**Comment by lmilbaum** [comment]
@robpearce-flux Thanks for filing this issue. I'm facing the same scenario. Would you mind clarifying what the stop command is?

**Comment by kayman-mk** [comment]
I wasn't aware of this script. I quickly checked one of my machines and found the script linked into `/etc/rc.d/rc5.d/S99remove_gitlab_registration`. Current runlevel is also 5. So from my knowledge this script is started in case the machine starts in runlevel 5. I verified that this is done as it creates a lockfile which is present `/var/lock/subsys/remove_gitlab_registration`

I also found the script in `/etc/rc.d/rc0.d/K03remove_gitlab_registration`. So it should remove the Runner registration on shutdown. But I wasn't able to find any log as the Systems Manager disconnects as soon as I terminate the instance and `/ var/log/messages` is no longer moved into Cloudwatch as well.

**Comment by kayman-mk** [comment]
The script itself works, I can confirm this.

```
 Overwrite token in SSM with null and remove runner from Gitlab
stop() {
    logger "Removing Gitlab Runner Token"
    aws ssm put-parameter --overwrite --type SecureString  --name "prod-gitlab-ci-runner-token" --region "eu-central-1" --value="null" 2>&1 | logger &
    curl -sS  --request DELETE "https://gitlab.my.instance/api/v4/runners" --form "token=my-token-here" 2>&1 | logger &
    retval=$?
    rm -f $lockfile
    return $retval
}
```

**Comment by kayman-mk** [comment]
Also not working with the SystemD service. Created and started one on the fly. But the token wasn't reset on shutdown.

**Comment by kayman-mk** [comment]
Tried to use absolute paths to all programs and removed the `| logger &`. But it didn't help. It seems that the script is not executed.

**Comment by kayman-mk** [comment]
Tried to follow https://github.com/miglen/aws/blob/master/ec2/run-script-on-ec2-instance-termination.md but it didn't help either.

**Comment by kayman-mk** [comment]
We could use the lifecycle hook which is triggered in case one of the Runners is terminating. But I will also ask my AWS contact for a solution.

**Comment by kayman-mk** [comment]
Received the following solution from my AWS contact:

```
/etc/system/system/onshutdown.service

[Unit]
Description=Run script at shutdown
After=network-online.target
Wants=network-online.target
Before=shutdown.target reboot.target halt.target kexec.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
ExecStop=/opt/on-shutdown

[Install]
WantedBy=multi-user.target


/opt/on-shutdown                                     
                                       
#!/usr/bin/bash
echo "Shutdown script"
echo "Shutdown triggered $(date)" >> /opt/shutdown.log
aws sqs send-message --queue-url https://sqs.eu-central-1.amazonaws.com/513725428015/Test --message-body "Shutdown triggered $(date)"


Installation
chmod +x /opt/on-shutdown
systemctl enable onshutdown
```
