### ISSUE TITLE
Since version 7.2.1 the old registration model no longer support removing the registration_token from the module

### ISSUE THREAD

**Issue by Atlasiscool** [cattle-ops/terraform-aws-gitlab-runner#1048]
# Describe the bug

After upgrading to 7.2.2 we could no longer remove the registration_token from our terraform file without the instance being disconnected from gitlab.

This works fine with the new registration model but breaks the old mechanism.

# To Reproduce

1. set module version to 7.2.1 or higher
2. set registration_token
3. apply
4. unset registration_token
5. apply

# Expected behavior

Runner automatically picks-up the token set in SSM parameter store.

# Additional context

If this is expected, please update the Release with this information !

---
Thank you for this great module !

**Comment by kayman-mk** [comment]
Yes, I can confirm this. The old token is used as long as it is available and valid.

As soon as the GitLab Runner EC2 instances are restarted, they will delete the old registration token and fetch a new one. So one restart (usually a module update to the next version) fixes that.
