### ISSUE TITLE
issue with pull_policies

### ISSUE THREAD

**Issue by brenol** [cattle-ops/terraform-aws-gitlab-runner#1065]
# Describe the bug

The `pull_policies` argument is not working as intented. From gitlab's own documentation only `pull_policy` and `allowed_pull_policies` are allowed: 

https://docs.gitlab.com/runner/executors/docker.html#:~:text=Use%20the%20following%20values%20for,local%20version%20does%20not%20exist.

# To Reproduce

Instead of:
```  
runner_worker_docker_options = {
    privileged            = "true"
    pull_policies = ["if-not-present"]
  }
```

Try:
```
  runner_worker_docker_options = {
    privileged            = "true"
    allowed_pull_policies = ["always", "if-not-present"]
  }
```

Running a runner with `if-not-present` crash makes it error out, as only `always` is allowed.

# Expected behavior

If not present works accordingly.

# Additional context

I think pull_policies should become allowed_pull_policies in the outputted config.toml, but I'm not sure as it is kinda like a breaking change to pipelines...

**Comment by kayman-mk** [comment]
`pull_policy` - the pull policy used by the Runner if none is specified in `.gitlab-ci.yml`. The default is `always`.
`allowed_pull_policies` - restricts the pull policies in the `.gitlab-ci.yml` to these values.

I'd like to introduce a `pull_policy` and leave the `pull_policies` as it is, marking it as deprecated and removing the code from `main.tf` as it is not working.

**Comment by kayman-mk** [comment]
Just thought about it again. Why not removing the `pull_policies` and replace it by `pull_policy`? It shouldn't break anything. Let me test this.

**Comment by kayman-mk** [comment]
Being a breaking change, I think, we can do this as the old option didn't have any influence and is simply not working. I introduce an error message in case `pull_policies` is used. So the migration is very easy.
