### ISSUE TITLE
v7.2.3 not available on Terraform Registry

### ISSUE THREAD

**Issue by jonpas** [cattle-ops/terraform-aws-gitlab-runner#1072]
# Describe the bug

Version 7.2.3 is not available on Terraform Registry

# To Reproduce

1. Go to https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest
2. Observe latest version being v7.2.2

# Expected behavior

v7.2.3 to be available

# Additional context

/

**Comment by rick** [comment]
Does the tagging style changing from `7.2.2` to `v7.2.3` have anything to do with this?

![Screenshot 2024-02-02 at 5 55 25 PM](https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/6259/90504e2a-27fd-4c79-982b-438128bbe4bf)

**Comment by rick** [comment]
Fwiw, I worked around this by pointing directly to the tag on this repo:

``` tf
module "gitlab_runner" {
  source      = "github.com/cattle-ops/terraform-aws-gitlab-runner?ref=v7.2.3"
```

**Comment by kayman-mk** [comment]
Ohhmm, that is strange and should not be the case. Every release should automatically available in the Terraform registry as well.

**Comment by kayman-mk** [comment]
Seems that the problem was introduced with the update of release-please to v4. The configuration changed and I overlooked it.

https://github.com/google-github-actions/release-please-action#upgrading-from-v3-to-v4

**Comment by kayman-mk** [comment]
This was not the real problem. Terraform registry supports `v` prefixes. I found out that the webhook which triggers the Terraform registry, doesn't work anymore. Instead the releases are sent to `npalm/gitlab-runner` which makes no sense. Have to reach out  @npalm to get this fixed.

**Comment by jonpas** [comment]
All releases are indeed available at https://registry.terraform.io/modules/npalm/gitlab-runner/aws/latest. Maybe some URL fall-back after rename expired.

**Comment by kayman-mk** [comment]
Hi @npalm could you please resync the Terraform module in the registry to setup a new GitHub webhook which hopefully works again?

https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest

**Comment by npalm** [comment]
Will check tonight

**Comment by npalm** [comment]
Resynced the module

<img width="924" alt="image" src="https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/11609620/e6a077b6-7fdc-483b-98d2-180d2acdba53">

**Comment by jonpas** [comment]
7.4.0 has the same issue, still not available on Terraform after 4 days of it being released.

**Comment by kayman-mk** [comment]
@npalm Could you please check again?

Repository settings are fine. The webhook is still there and marked as active.

**Comment by npalm** [comment]
Juat re-synced the module in the registry (manually). No clue why it did not synced. For another module I had the problem as well some weeks ago. There we release including the `v` prefix. But last weeks no issues.

**Comment by tibuntu** [comment]
I still can't see `7.4.0` in the Terraform registry

**Comment by jonpas** [comment]
> I still can't see `7.4.0` in the Terraform registry

You are probably looking at old npaln's registry, this is the proper one: https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest

**Comment by tibuntu** [comment]
@jonpas that makes sense. Thanks for pointing that out!

**Comment by npalm** [comment]
<img width="773" alt="image" src="https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/11609620/95cb7e4b-4f41-48f8-ba65-d136fe1bcbd7">

7.4.0 is in the registry
