### ISSUE TITLE
Module update removes registered runner but does not create a new runner

### ISSUE THREAD

**Issue by jonpas** [cattle-ops/terraform-aws-gitlab-runner#1074]
# Describe the bug

Updating GitLab Runner version by re-deploying a Terraform project using this module with the new "Next GitLab Runner Token Architecture", as the new EC2 instance is created, GitLab Runner is removed from the GitLab instance, but a new one is not registered.

Before "Next GitLab Runner Token Architecture", the GitLab Runner was simply updated.

# To Reproduce

1. Update `runner_gitlab = { runner_version = "16.7.0" }` to a newer version (eg. `16.8.0`)
2. `terraform plan` + `terraform apply`
3. Observe new master runner instance being created on EC2 and old one destroyed
4. Observe runner being deleted from GitLab instance
5. Wait and observe no new runner being created on the GitLab instance
6. Have no runner

# Expected behavior

A GitLab Runner to either be recreated or re-use the existing runner registration.

# Additional context

Upgrade to "Next GitLab Runner Token Architecture" was performed with a completely fresh setup, no old SSM parameters remained. We deploy using and GitLab's Terraform state handling through GitLab's CI (running on a instance completely separated from any auto-deployed ones from this module).

We have to fully destroy the runner and recreate it to get the runner re-registered. EC2 system logs show nothing different from the past, but I can supply a log if no other ideas are available.

**Comment by jonpas** [comment]
There are multiple SSM parameter tokens created:
- `*-access-token` holding the `glpat-*` token (GitLab Access Token for registering Runners)
- `*-<name>-runner-token` holding the `glrt-` token _(no description)_
- `*-<name>-sentry-dsn` holding `null` _(no description)_

My configuration is similar except it's an instance runner.
```tf
  runner_gitlab = {
    runner_version                           = "16.8.0"
    url                                      = "https://gitlab...."
    access_token_secure_parameter_store_name = "gitlab-runner-access-token"
  }

  runner_gitlab_registration_config = {
    type              = "instance"
    tag_list          = "tag1,tag2"
    description       = "name"
    locked_to_project = "false"
    run_untagged      = "true"
    maximum_timeout   = "3600"
  }
```

Anyways, after updating to 7.3.1, it has re-registered itself correctly first try. I wonder if #1058 fixed the issue in this case.

**Comment by lpsm-nuageit** [comment]
is there any way of setting this up without having to register a runner? i already have my runner created in the visual interface

**Comment by kayman-mk** [comment]
Yes, that is possible. We added a variable in the last release.

There is also a PR ongoing to allow zero downtime updates.
