### ISSUE TITLE
Support Docker option for IPv6

### ISSUE THREAD

**Issue by william00179** [cattle-ops/terraform-aws-gitlab-runner#1094]
# Describe the solution you'd like

I'm trying to use the runner in a IPv6 only environment. The runner itself works well and is able to connect to my Gitlab instance, but when the job starts within its own docker container it gets a connection timeout to Gitlab as its not able to make use of the IPv6 networking. 

To allow this to work, `enable_ipv6` needs to be set in the Docker configuration otherwise docker networks don't support it. 

See https://docs.docker.com/config/daemon/ipv6/ and https://gitlab.com/gitlab-org/gitlab-runner/-/issues/36994

# Suggest a solution

Add the enable_ipv6 flag to [runner_worker_docker_options](https://github.com/cattle-ops/terraform-aws-gitlab-runner?tab=readme-ov-file#input_runner_worker_docker_options). Note the `enable_ipv6` documentation is currently missing, see the issue above.

**Comment by kayman-mk** [comment]
Seems to be mandatory, if you want to IPv6 only.

**Comment by kayman-mk** [comment]
@william00179 Are you working in a IPv6 only setup? There is #1075  claiming that SSM access in not working for IPv6 only so the Runner will not be able to start.
