### ISSUE TITLE
Releases not present in the Terraform registry

### ISSUE THREAD

**Issue by tibuntu** [cattle-ops/terraform-aws-gitlab-runner#1111]
# Describe the bug

The recently released version 7.5.0 was not yet published in the Terraform registry.

AFAIR this has already happened with a previous version

# To Reproduce

1. Visit https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest
2. Latest available version is `7.4.0`

# Expected behavior

Version `7.5.0` is available in the registry

**Comment by kayman-mk** [comment]
@npalm Can you please resync the Terraform registry? No idea what's going wrong here. Webhook looks good. I don't see any errors.

**Comment by npalm** [comment]
On it, but there are no secrets. Publishing a module is just a one time action and next hashicopr should keep it working

**Comment by npalm** [comment]
solved, re-synced

**Comment by tibuntu** [comment]
Can confirm, thanks for taking care!

**Comment by gmeligio** [comment]
Hi. This seems to be happening again for [7.6.0](https://github.com/cattle-ops/terraform-aws-gitlab-runner/releases/tag/7.6.0). It was released yesterday, but in [Terraform Registry](https://registry.terraform.io/modules/npalm/gitlab-runner/aws/latest) appears up to 7.5.0. Unfortunately, I don't have more information on why this could happen.

Could you, @npalm, please look again? Thank you.

**Comment by gmeligio** [comment]
By the way, I checked both the [old module link](https://registry.terraform.io/modules/npalm/gitlab-runner/aws/latest) and the [new module link](https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest), and they are both up to 7.5.0

I read the [Registry FAQ](https://developer.hashicorp.com/terraform/registry/faq) but found nothing relevant.

If it happens often, asking Hashicorp could help identify the issue.
https://developer.hashicorp.com/terraform/registry#getting-help

**Comment by gmeligio** [comment]
To add more context, this kind of out-of-sync issue has happened at least once, even to the AWS provider. They said they solved it by talking internally to the Registry Team. So it seems emailing Hashicorp could be a potential option for further investigation.
https://github.com/hashicorp/terraform-provider-aws/issues/33588

**Comment by npalm** [comment]
I have manually synced the module. Still no clue why it stopped working.

**Comment by Unibozu** [comment]
Hi @npalm 

Not sure this fixed the problem with 7.6.0, the registry remains on 7.5.0 being the latest.

![image](https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/1690498/fb472b20-8d1c-4bb2-aa0c-cb08a5bbfdd5)

```
│ There is no available version of module
│ "registry.terraform.io/npalm/gitlab-runner/aws" (main.tf:51) which matches
│ the given version constraint. The newest available version is 7.5.0.
```

**Comment by gmeligio** [comment]
@Unibozu, you can find it in the new module link: https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/latest

I guess the old one is updated periodically, but it seems better to use the new one with the same name as the GitHub organization.

**Comment by kayman-mk** [comment]
@npalm Can we tear down the old npalm/... Terraform module?

**Comment by npalm** [comment]
I have deleted the module npalm/. and triggered another resync. Let's see if it is working. In case we keep the problems. I will re-create the cattle-ops one.

**Comment by kayman-mk** [comment]
7.6.1 published without problems.
