### ISSUE TITLE
Runner token usage counter not decrementing when terminating old instance

### ISSUE THREAD

**Issue by long-wan-ep** [cattle-ops/terraform-aws-gitlab-runner#1136]
# Describe the bug

The usage counter in the runner token SSM parameter is not decrementing when old runner instances are terminated. I feel like [remove-gitlab-registration.service](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/main/template/gitlab-runner.tftpl#L196) is not running on termination, since I don't see the expected "Token still in use. GitLab Runner not removed from GitLab." message in the logs.

# To Reproduce

1. Deploy a runner on version 7.7 of the module
2. Verify the usage counter for the runner token SSM param is 1
3. Make a update to the runner config that would result in a runner refresh
4. Wait for graceful terminate to complete and the old runner instance is terminated
5. Check the usage counter again, which will show 2 instead of 1

# Expected behavior

The usage counter should increment when a new runner instance spins up, and decrement when an old runner instance terminates.

**Comment by kayman-mk** [comment]
Can you upgrade to pre-registered Runners? `runner_gitlab.preregistered_runner_token_ssm_parameter_name`

As far as I remember, this JSON solution is not 100% accurate and should prevent the Runner from being de-registered in case it is still in use. The whole code is deprecated as the GitLab guys are not switching to pre-registered Runners.

**Comment by long-wan-ep** [comment]
Gotcha, thanks closing this issue.
