### ISSUE TITLE
Support for Amazon Linux 2023

### ISSUE THREAD

**Issue by scamp** [cattle-ops/terraform-aws-gitlab-runner#1137]
# Describe the solution you'd like

Machine bootstrap procedure needs to be updated for newer AMZ linux releases.
Deploying gitlab-runner to Amazon Linux 2.0 can be affected by https://gitlab.com/gitlab-org/gitlab-runner/-/issues/37366

# Describe alternatives you've considered

At the moment setting up runner_ami_filter to al2023-ami-2023*-x86_64 does not result in successful deployment.
Provisioning script fails at installing awslogs package and times out on retry.

**Comment by antoniodfr** [comment]
Hi, we have started to have problems with Amazon Linux v2, as it contains Python 3.7, and the new versions of AWS CLI requires Python 3.8. We think supporting Amazon Linux 2023 will solve this problem. Thank you!
