### ISSUE TITLE
Report an error when the ssm key doesn't exist

### ISSUE THREAD

**Issue by lmilbaum** [cattle-ops/terraform-aws-gitlab-runner#1139]
# Describe the solution you'd like

Fail the apply if the SSM access key is not found

**Comment by kayman-mk** [comment]
@lmilbaum Could you please add some details? Not sure what you mean.

**Comment by lmilbaum** [comment]
> @lmilbaum Could you please add some details? Not sure what you mean.

I forgot to setup the SSM access key before deployment.  No error reported.  But, the runner didn't work as expected.

**Comment by kayman-mk** [comment]
This one? `var.runner_gitlab.preregistered_runner_token_ssm_parameter_name`

**Comment by lmilbaum** [comment]
> This one? `var.runner_gitlab.preregistered_runner_token_ssm_parameter_name`

The key was populated with a name but I didn't created the resource in AWS
