### ISSUE TITLE
Unable to fetch the jobs and register runners with gitlab-ee self-hosted

### ISSUE THREAD

**Issue by jaydeeppromact2024** [cattle-ops/terraform-aws-gitlab-runner#1143]
# Unable to fetch the jobs and register runners with GitLab enterprise edition self-hosted

### GitLab enterprise edition - (self-hosted)
Version = [v17.1.1-ee](https://gitlab.com/gitlab-org/gitlab/-/tags/v17.1.1-ee)
----
### Gitlab Runner
Version = 17.1
----
### Used Runner-default template to deploy
[examples/runner-default](https://github.com/cattle-ops/terraform-aws-gitlab-runner/tree/main/examples/runner-default)
----
### Getting errors
1] "level":"error","msg":"Checking for jobs... forbidden","runner":"GR1348941xXzhePNZ","status":"POST https://gitlab.example.com/api/v4/jobs/request: 403 Forbidden"

2] "error","msg":"Runner \"https://gitlab.example.comGR1348941xXzhePNZ\" is unhealthy and will be disabled for 1h0m0s seconds

----

## Screenshots

![image](https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/169680007/6327266f-0f56-420d-af09-c640d522e7ab)

![image](https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/169680007/5bd4ddfc-12a4-4db3-a94c-c546cd2f6f81)

----
please help

**Comment by qyd159** [comment]
encountering the same problem

**Comment by jhelbling** [comment]
still present

**Comment by kayman-mk** [comment]
Have you checked the `config.toml` and see the correct Runner token? In case of using own AMIs: try the default ones which are set by the module.
