### ISSUE TITLE
GitLab Runner 15.8.2 can't be installed on Amazon Linux 2023

### ISSUE THREAD

**Issue by nexonen** [cattle-ops/terraform-aws-gitlab-runner#1147]
# Describe the bug

**Module version:** 7.8.0

After the [update](https://github.com/cattle-ops/terraform-aws-gitlab-runner/pull/1138) to use Amazon Linux 2023, the runner version 15.8.2 isn't available to be installed as it isn't found in the package repository. Version 15.8.2 is the default version specified in [variables.tf](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/321efff8365ae7ac3f604d56561f186958d0d608/variables.tf#L338).

A list of gitlab-runner packages released for Amazon Linux 2023 is [here](https://packages.gitlab.com/app/runner/gitlab-runner/search?q=&filter=rpms&filter=rpms&dist=amazon%2F2023).

# To Reproduce

1. Provision a new runner using module version 7.8.0 with gitlab-runner version 15.8.2
2. Observe that the runner doesn't connect to the gitlab instance after registration
3. Connect to the instance and look at the logs in `/var/log/messages`, see `Error: Unable to find a match: gitlab-runner-15.8.2`
4. Observe that gitlab-runner package is not installed

# Expected behavior

An available version of gitlab-runner should be specified as the default for the `runner_gitlab.runner_version` variable.

**Comment by kayman-mk** [comment]
Gosh, I wasn't aware of this. Absolutely true. I prefer to not use the default as the Runner should match to your GitLab version. Maybe we should make this a mandatory parameter?
