### ISSUE TITLE
run_untagged option shouldn't be deprecated

### ISSUE THREAD

**Issue by dimashenkov** [cattle-ops/terraform-aws-gitlab-runner#1169]
# Describe the bug

run_untagged option shouldn't be deprecated , regarding  the documentation it was depreciated  with [runner_gitlab_registration_config](https://registry.terraform.io/modules/cattle-ops/gitlab-runner/aws/7.9.0#input_runner_gitlab_registration_config)

# Expected behavior
It would be good to have  a way to set this with terraform.

**Comment by kayman-mk** [comment]
This option won't be deprecated. Instead you have to register the Runner manually on the GitLab UI and use that token for the module. The GitLab guys removed the API to register a new Runner. So we can't use this feature any longer (GitLab 17+).

Pass the token of the manually created Runner to `var.runner_gitlab.preregistered_runner_token_ssm_parameter_name`.
