### ISSUE TITLE
Need quotes for update_interval and update_interval_when_expecting config values

### ISSUE THREAD

**Issue by pokidovea** [cattle-ops/terraform-aws-gitlab-runner#1176]
# Describe the bug

`update_interval` and `update_interval_when_expecting` config values are rendered without quotes what leads to the parsing error:
```
    update_interval = 1m
    update_interval_when_expecting = 2s
```
Unexpected character, expected only whitespace or comments till end of line

Adding quotes like below solves the problem
```
    update_interval = "1m"
    update_interval_when_expecting = "2s"
```

## Additional info 
terraform-aws-gitlab-runner v7.13.0

**Comment by kayman-mk** [comment]
Arrgh, that's true.
