### ISSUE TITLE
Pass an EIP to the EC2 instance created

### ISSUE THREAD

**Issue by bsuv** [cattle-ops/terraform-aws-gitlab-runner#124]
In some cases when using spot, I'd like to be able to provide an EIP and reuse them in case the spot is terminated. 

This is useful to prevent changing inbound rules that uses the runner's public IP as a source in their inbound rule.

**Comment by npalm** [comment]
@bsuv feel free to propose a PR. I use the runners in a private subnet, so no public ones are attached.

**Comment by bsuv** [comment]
I will work on a PR. The issue with having them in a private subnet is that the NAT Gateway costs can become prohibitive

**Comment by roock** [comment]
related issue #92

**Comment by roock** [comment]
I've started working on this issue: https://github.com/roock/terraform-aws-gitlab-runner/commit/bab9354d53e1db549e311c73d56fc2cd944bcb69
it is working when enabling the use of EIP, but for disabling the feature I need a way to reference a non existing object (aws_eip is only create if the flag is set)

**Comment by kostyrev** [comment]
@roock do not hard code region and please do rebase from upstream and open PR

**Comment by roock** [comment]
@kostyrev ups, thx for the hint

**Comment by roock** [comment]
Assignment of EIP to the Runner server itself was added in #161 and #165. Not sure if it is possible to add support for EIPs for the docker-machine servers though.

**Comment by npalm** [comment]
@roock seems not supported by the aws docker machine driver https://docs.docker.com/machine/drivers/aws/

**Comment by roock** [comment]
A possibility would be to use the user_data to assign an EIP to the docker-machine instances.

**Comment by kayman-mk** [comment]
Is it really necessary to expose the runners? You could also access your machines via AWS Console (SSM access). Seems to be easier to configure and less risky.

If we are talking about the agent: There should be an inbound rule which allows traffic from your Gitlab instance only.

We should be fine without an EIP at all or do I miss something? Any other use case?
