### ISSUE TITLE
Remove the support for register the runner outside the module

### ISSUE THREAD

**Issue by npalm** [cattle-ops/terraform-aws-gitlab-runner#186]
Due to backwards compatibly the module still supports the scenario to register a runner manual and pass the token. To reduce the complexity and number of scenarios this option will be removed.

**Comment by trallnag** [comment]
A major version bump that throws out a bunch of deprecated stuff would be great

**Comment by npalm** [comment]
fully agree, feel free to create a PR

**Comment by kayman-mk** [comment]
@npalm As we always have to store the token somewhere: Which option should be removed (you are referring in your first post)?

**Comment by dsalaza4** [comment]
We're currently having issues with the parameter store after upgrading from 6.3.1 to 6.5.2. 

This only happens when we run a `terraform plan` with a read-only role. A `terraform deploy` works fine.

Logs say:

```
│ Error: reading SSM Parameter (ci-common-large-x86-0-sentry-dsn): InvalidKeyId: arn:aws:kms:us-east-1:205810638802:key/b1bd2030-d46d-41b7-89ef-3ed07a9181fb is pending deletion. (Service: AWSKMS; Status Code: 400; Error Code: KMSInvalidStateException; Request ID: 81ba4e7e-f4b0-4f76-b1c3-9f6df3eac93f; Proxy: null)
│ 
│   with module.runners["common-large-x86-0"].aws_ssm_parameter.runner_sentry_dsn,
│   on .terraform/modules/runners/main.tf line 27, in resource "aws_ssm_parameter" "runner_sentry_dsn":
│   27: resource "aws_ssm_parameter" "runner_sentry_dsn" {
```

When inspecting the parameter store I see this:

<img width="939" alt="image" src="https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/11205987/286307c2-0812-4214-bb34-0fe9967f1e21">

I will try removing all parameters and letting the module recreate them to see what happens.

**Comment by dsalaza4** [comment]
> We're currently having issues with the parameter store after upgrading from 6.3.1 to 6.5.2.
> 
> This only happens when we run a `terraform plan` with a read-only role. A `terraform deploy` works fine.
> 
> Logs say:
> 
> ```
> │ Error: reading SSM Parameter (ci-common-large-0-sentry-dsn): AccessDeniedException: User: arn:aws:sts::205810638802:assumed-role/dev/gitlab-20741933-1014135500-5149570679 is not authorized to perform: kms:Decrypt on resource: arn:aws:kms:us-east-1:205810638802:key/a4f312cd-f0bf-4701-9cbe-d044996161ec because no identity-based policy allows the kms:Decrypt action (Service: AWSKMS; Status Code: 400; Error Code: AccessDeniedException; Request ID: 0a802a13-e844-4f89-9d8f-9c31880dff35; Proxy: null)
> │ 	status code: 400, request id: 7de4acec-8047-4ef5-a14d-d042971c1375
> ```
> 
> Keys went to a `pending deletion` state after making `enable_kms = false`, but ssm parameters kept pointing to them:
> 
> ```
> │ Error: reading SSM Parameter (ci-common-large-x86-0-sentry-dsn): InvalidKeyId: arn:aws:kms:us-east-1:205810638802:key/b1bd2030-d46d-41b7-89ef-3ed07a9181fb is pending deletion. (Service: AWSKMS; Status Code: 400; Error Code: KMSInvalidStateException; Request ID: 81ba4e7e-f4b0-4f76-b1c3-9f6df3eac93f; Proxy: null)
> │ 
> │   with module.runners["common-large-x86-0"].aws_ssm_parameter.runner_sentry_dsn,
> │   on .terraform/modules/runners/main.tf line 27, in resource "aws_ssm_parameter" "runner_sentry_dsn":
> │   27: resource "aws_ssm_parameter" "runner_sentry_dsn" {
> ```
> 
> When inspecting the parameter store I see this:
> 
> <img alt="image" width="939" src="https://user-images.githubusercontent.com/11205987/270084142-286307c2-0812-4214-bb34-0fe9967f1e21.png">
> I will try removing all parameters and letting the module recreate them to see what happens.

Manually removing all parameters and running a deploy with `enable_kms = false` recreated them with `alias/aws/ssm`. At this point running a `terraform test` with the read-only role worked fine.

If we try to set `enable_kms = true` again, terraform states that it will change the kms key for all parameter stores to the custom key again.

I would rather use aws managed keys for this, does `enable_kms = true` mean that things are not being encrypted or that things are being encrypted using aws managed keys?

**Comment by kayman-mk** [comment]
This seems to be a valid point, yes. Could you please create a separate issue for this, @dsalaza4 ?

**Comment by kayman-mk** [comment]
Planned for the v8 release end of 2024

**Comment by kayman-mk** [comment]
Will close this now as this is the official strategy from GitLab to handle Runners. Register them manually and go with it.
