### ISSUE TITLE
Specify multiple instance_types for docker_machine_instance_type

### ISSUE THREAD

**Issue by jschelfh-be** [cattle-ops/terraform-aws-gitlab-runner#414]
Can _docker_machine_instance_type_ be made a list so that you can specify multiple instance types, thus increasing the change of getting a spot instance. Currently configured using 1AZ, it happened several times that I was not able to get an EC2 of type t3.medium, but other spot instance types were available

**Comment by npalm** [comment]
Would be a great feature, but not supported well by the underlying frameworks. A lot of work was done in this PR to make it possible #249

**Comment by kayman-mk** [comment]
Yeah, that's another thing which could work. Spawn agents with runners of different EC2 types. Not exactly what ylu want, but 80%.

I suggest to use at least 2 AZs. Just in case.
