### ISSUE TITLE
Add support for shell executor

### ISSUE THREAD

**Issue by ivankovnatsky** [cattle-ops/terraform-aws-gitlab-runner#416]
Would be great to be able to configure shell executor: https://docs.gitlab.com/runner/executors/shell.html

**Comment by kayman-mk** [comment]
@ivankovnatsky Could you provide more details please? At the moment I do not see any advantage of supporting another runner type. But there might be use cases I do not know. What is the advantage of a shell runner?

**Comment by ivankovnatsky** [comment]
I usually don't build container images using docker-in-docker, so I thought it would be great to have a shell runner with docker. 

But yeah, if community does not feel it's necessary, that might not make sense to do it.

**Comment by kayman-mk** [comment]
Could be a nice extension, @ivankovnatsky Any chance to get a PR from you on how to change the current template to support other executors?

**Comment by kayman-mk** [comment]
I quickly checked the linked documentation. In the current setup we have one Gitlab Runner + many executors (docker machines). The shell executor is running on the runner directly. So there are no executors and thus this might create problems with higher workloads (no scaling). This can be fixed by deploying the module several times of course.

**Comment by ivankovnatsky** [comment]
> Could be a nice extension, @ivankovnatsky Any chance to get a PR from you on how to change the current template to support other executors?

sure, though can quite promise the timing.

**Comment by lmilbaum** [comment]
@ivankovnatsky I have a similar need.  How did you solve this issue?

**Comment by kayman-mk** [comment]
@lmilbaum Could you please elaborate on your use case? Can it be solved with the `docker` or `docker+machine` executor?
