### ISSUE TITLE
Race condition around elastic IP

### ISSUE THREAD

**Issue by davidnortonjr** [cattle-ops/terraform-aws-gitlab-runner#442]
We have `enable_eip = true`, and it seems to cause a race condition when rolling out a deployment on the GitLab Runner ASG. If the new instance tries to assign the IP before the old instance has shut down / released it, then it fails to come up cleanly and does not pick up jobs.

I'm not sure the best way to solve this, but perhaps either (or both):
1. a retry / backoff for assigning the EIP in [eip.tpl](https://github.com/npalm/terraform-aws-gitlab-runner/blob/36633fa6286343cce72b0d9c0c3451305a36be11/template/eip.tpl#L10)
2. some sort of health check to automatically restart/replace the instance as a whole if it never comes up cleanly

**Comment by npalm** [comment]
Sorry cannot help, hope someone in the community can. We are not using EIP.
