### ISSUE TITLE
cancel-spot-instances.sh fails in Terraform container

### ISSUE THREAD

**Issue by Leonidimus** [cattle-ops/terraform-aws-gitlab-runner#493]
This module "npalm/gitlab-runner/aws" is meant to be run in a Terraform container, however script `bin/cancel-spot-instances.sh` doesn't work because it requires bash which doesn't exist in Terraform images. Terraform images only have sh. Besides, the script also requires jq and awscli which don't exist either in Terraform alpine based images.

I get this error:
```
│ Error: local-exec provisioner error
│ 
│   with null_resource.cancel_spot_requests,
│   on main.tf line 142, in resource "null_resource" "cancel_spot_requests":
│  142:   provisioner "local-exec" {
│ 
│ Error running command
│ './.terraform/modules/gitlab-runner/bin/cancel-spot-instances.sh
│ voice-runners': exit status 127. Output: env: can't execute 'bash': No such
│ file or directory
```

**Comment by npalm** [comment]
Thanks for reporting. I see not another way to cancel spot instances when destroy than using a local executor. We could explore the following options:

- Run in `/bin/sh`
- Add an op-out flag for the script

**Comment by kayman-mk** [comment]
As far as I remember this null_resource has been removed some time ago. Could you please check the module version you are using? Any chance to update to 5.0.2?

**Comment by kayman-mk** [comment]
To be tackled in #623 as we need an option to remove resources created during runtime.

**Comment by npalm** [comment]
The script was created to support the examples (for testing purpose).
