### ISSUE TITLE
wait_for_services_timeout parameter not supported

### ISSUE THREAD

**Issue by DnD-Magnum** [cattle-ops/terraform-aws-gitlab-runner#513]
Hello,

First, thank you very much for this very good module ! 
 
We search to increase [wait_for_services_timeout](https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersdocker-section) runner parameter but, it seems that this parameter is not implemented in the module.

Do you plan to develop it in the roadmap?

Best regards,
Geoffrey

**Comment by kayman-mk** [comment]
See #511 Created the PR yesterday to restructure the variable sections and make it easy to add all other Docker options.
