### ISSUE TITLE
Allow passing existing roles to docker machine

### ISSUE THREAD

**Issue by dsalaza4** [cattle-ops/terraform-aws-gitlab-runner#524]
We currently have `docker_machine_iam_policy_arns`, but that one only allows to specify which policies to attach to the role-to-create. 

I have a use case in which I want to use an existing role for the workers.

Something like `docker_machine_role_arn` would do. It could be used to create the instance profile.

**Comment by dsalaza4** [comment]
I just noticed we also have `runners_iam_instance_profile_name`. We could also do `workers_iam_instance_profile_name`

**Comment by dsalaza4** [comment]
After reviewing [this line](https://github.com/npalm/terraform-aws-gitlab-runner/blob/5b7bf4ce3ef912e40f9694e8b38e5a5b87b1e65d/template/runner-config.tpl#L63) I found out that `runners_iam_instance_profile_name` is indeed the parameter I needed. 

I think right now we use something close the following convention:

1. inputs with the `runner` prefix refer to the _Gitlab orchestrator_ or _bastion_.
2. inputs with the `runners` prefix refer to the _machines running the jobs_ or _workers_.

@npalm What do you think about renaming the `runners` prefix to `worker`?

For example:

```terraform
  worker_ebs_optimized = true
  worker_idle_count    = 3
  worker_idle_time     = 1800
```

We could also add the according prefix to some other variables like `subnet_ids_gitlab_runner` or `enable_runner_ssm_access`.

Thank you so much for maintaining this project BTW!

**Comment by kayman-mk** [comment]
According to the GitLab documentation I suggest `Agent` and `Executor`

**Comment by dsalaza4** [comment]
@kayman-mk Can you please provide a reference for this? I would like to read more about it. Thanks!

**Comment by kayman-mk** [comment]
The project is known as Gitlab Runner: https://gitlab.com/gitlab-org/gitlab-runner. Documentation is available at: https://docs.gitlab.com/runner/

The page mentions the Executors (diagram at the bottom). What I have called Agent is shown as "GitlabRunner". In the paragraph "Runner registration" they name it Agent.

I think to avoid confusions, it's better not to use the word "Runner".
