### ISSUE TITLE
Change var.runners_add_dind_volumes to share /builds

### ISSUE THREAD

**Issue by UnknownGnome** [cattle-ops/terraform-aws-gitlab-runner#537]
Changing var.runners_add_dind_volumes in locals.tf <https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/locals.tf#L22>  to change `"/builds"` to `"/builds:/builds"` would simplify sharing volume mounts to dind containers. 
https://gitlab.com/gitlab-org/gitlab-foss/-/issues/41227#note_294252441

**Comment by kayman-mk** [comment]
Sounds interesting, but I am not very familiar with the setup. What is the difference between `/builds` and `/builds:/builds`? Is there any documentation available?

**Comment by kayman-mk** [comment]
@UnknownGnome Could you please explain the difference between the setups? What does change if I mount `/builds:/builds` instead of `/builds`? The Docker documentation was not helpful for me.
