### ISSUE TITLE
Possible race condition with aws_iam_role.instance recreate

### ISSUE THREAD

**Issue by dzinek** [cattle-ops/terraform-aws-gitlab-runner#583]
Hi, I decided to upgrade module from version 5.4.1 to 5.5.0 due to fixed #557.

Plan showed me that ASG Launch Template will be changed (due to changes in `user_data` with pull policy and gzip from #565).
But also the `aws_iam_role.instance` has to be recreated:
```
  # module.gitlab_runner.aws_iam_role.instance will be destroyed
  # (because resource uses count or for_each)
  - resource "aws_iam_role" "instance" {
```
and then
```
  # module.gitlab_runner.aws_iam_role.instance[0] will be created
  + resource "aws_iam_role" "instance" {
```

The plan looked good (first destroy role then create it) so I applied it.
Changes with launch template and ASG passed, but role recreation failed - seems like the race condition - the new role is starting to create, when the old one has not finish destroying:
```
module.gitlab_runner.aws_iam_role.instance: Destroying... [id=runner-instance]
module.gitlab_runner.aws_iam_role.instance[0]: Creating...
module.gitlab_runner.aws_iam_role.instance: Destruction complete after 3s
╷
│ Error: failed creating IAM Role (runner-instance): EntityAlreadyExists: Role with name runner-instance already exists.
│ 	status code: 409, request id: xxxxxxx
│
│   with module.gitlab_runner.aws_iam_role.instance[0],
│   on .terraform/modules/gitlab_runner/main.tf line 331, in resource "aws_iam_role" "instance":
│  331: resource "aws_iam_role" "instance" {
```

I need to run apply three times - 1st one to got this error, and also another two times to pass it.

The final state was, that the new runner cannot be registered, due to issue in `user_data` with fetching runner token from SSM. The instance profile lost the assigned role, so the ec2 could not fetch any data from SSM.
I had to reassign role to instance profile manually to fix the access and have runner registered.

**Comment by kayman-mk** [comment]
Can't confirm this using Terraform 1.3.2

Plan says: 
`module.gitlab_runner.module.gitlab_runner_test["subnet-xyz"].aws_iam_role.instance has moved to module.gitlab_runner.module.gitlab_runner_test["subnet-xyz"].aws_iam_role.instance[0]`.

The resource is not destroyed and recreated.

**Comment by dzinek** [comment]
Ok, we are in process of migration to 1.3.5 - will test it on the later TF.

**Comment by kayman-mk** [comment]
Seems to be related to #591

**Comment by kayman-mk** [comment]
Any news here, @dzinek? Or can we close this issue?
