### ISSUE TITLE
Clean SSH key pairs in AWS

### ISSUE THREAD

**Issue by dsalaza4** [cattle-ops/terraform-aws-gitlab-runner#592]
We recently hit the AWS quota for the maximum number of SSH key pairs:

![image](https://user-images.githubusercontent.com/11205987/206300827-f05fd9d3-bc98-4c6a-84ee-c90307e20499.png)

Around 4000 of the keys were created by the runner when provisioning machines and left there.

It looks like the runner does not remove the associated key pair when removing a worker.

I would like to be able to:

Not use SSH keys at all (only SSM). I do not know if this is possible, as it looks like docker machine uses those keys for keeping runner-worker communication.

OR

Specify one single key for all workers so they do not get created on demand.

As a temporary fix I created a schedule that cleans all unused CI ssh keys: https://gitlab.com/fluidattacks/universe/-/issues/8300

Thank you so much for all the effort you've put in this module!

**Comment by kayman-mk** [comment]
Same problem here. Have a Lambda running to clean up unused resources.

**Comment by kayman-mk** [comment]
We should add a Lambda function to the module to clean up the unused key pairs every day. This module should not leave unused resources in the AWS account.
