### ISSUE TITLE
Implement new GitLab Runner Autoscaling architecture

### ISSUE THREAD

**Issue by kayman-mk** [cattle-ops/terraform-aws-gitlab-runner#624]
Docker+machine is outdated and the Gitlab group is developing on a new infrastructure (taskscaler + AWS fleeting).

This module should move away from the old Docker+machine and support the new Gitlab plugin technology.

Refs:
https://docs.gitlab.com/ee/architecture/blueprints/runner_scaling/index.html
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29312
https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29219#note_1169146211

**Comment by npalm** [comment]
Fully agree docker machine is outdated. And as soon GitLab has something ready we should ty to adopt the new direction.

**Comment by NK74** [comment]
Any news about this ?

**Comment by kayman-mk** [comment]
Do we have a link at hand on how to use this new feature, which GitLab version I need, ....?

**Comment by Kadeux** [comment]
I'm currently working on this issue but the lack of documentation (source code mostly) makes it really difficult. I'm planning to continue my work when the beta will be released ([16.2](https://gitlab.com/gitlab-org/gitlab-runner/-/issues/29404)).

For those who might be interested, my error is `ERROR: Failed to remove network for build` when the runner is trying to `dial` the newly created instance.

**Comment by kayman-mk** [comment]
Did a quick analysis. Some people suggest that a) Docker is missing on the machine and b) the Runner is not running in privileged mode. But I guess if you take your standard configuration it should work out of the box.

**Comment by veshant** [comment]
They've added it to the official docs

https://docs.gitlab.com/runner/executors/docker_autoscaler.html#example-aws-autoscaling-for-1-job-per-instance

**Comment by lenasappvia** [comment]
This will be great to add!

**Comment by dsalaza4** [comment]
Would love to see this!

Tired of Docker+machine errors, they're so hard to debug 😿

**Comment by nesty92** [comment]
Hey everyone,

[GitLab Runner Autoscaler for AWS](https://registry.terraform.io/modules/nesty92/gitlab-runner-autoscaler/aws/latest)

Since I didn't have enough time to integrate it here, I decided to start from scratch. I've also included the Packer file for building the AMI.

Give it a try, share your feedback, and even contribute to make it even better!

Happy scaling! 🚀🔧

**Comment by kayman-mk** [comment]
Closed via #1118
