### ISSUE TITLE
Spawn Windows ECR images?

### ISSUE THREAD

**Issue by rewb0rn** [cattle-ops/terraform-aws-gitlab-runner#775]
Hello,

will I be able to spawn Windows based ECR images from a gitlab runner that is using the "docker+machine" executor? The runner manager seems to require a linux based AMI but what about the ECR images? Since they are running on new EC2 instances, I think there might be a chance that it would work?

Thanks in advance

**Comment by kayman-mk** [comment]
Give it a try. The spawned EC2 machine has Docker installed and can execute any Docker image. So there shouldn't any dependency to Windows or Linux at all.

**Comment by npalm** [comment]
The docker-machines are linux x64 based. Which means you can only run linux x64 based docker containers. Windows containers won't work.
