### ISSUE TITLE
Security: registration token is stored in plan text in user-data

### ISSUE THREAD

**Issue by ekini** [cattle-ops/terraform-aws-gitlab-runner#776]
# Describe the solution you'd like

The runner token is stored in the SSM Parameter store but the registration token is just there in plain text.
It would make sense to get it dynamically from another parameter. That parameter can possibly be managed externally.

# Describe alternatives you've considered

# Suggest a solution

1. (option 1). Create an SSM parameter with provided registration token. Get the token dynamically from it.
2. (option 2). Point user-data to the ssm parameter to get the token from it. This way the SSM parameter can be managed externally and the token doesn't end up in the terraform state.

# Additional context

Not sure if it's worth creating another issue. The provided IAM policy allows reading *all* SSM parameters. It doesn't seem like it's required and access should be scoped down to one resource (or 2 if the registration token is placed in there as well).

**Comment by kayman-mk** [comment]
See #822 which implements option 2.

**Comment by ekini** [comment]
Thank you!
