### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock

### ISSUE THREAD

**Issue by SomaGallai** [cattle-ops/terraform-aws-gitlab-runner#779]
# Describe the bug

Getting `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock` error when trying to authenticate with AWS ECR. The runner is supposed to authenticate to create Docker image for ECR. The following setting has been turned on to enable the correct DIND settings `runners_add_dind_volumes = true`

# To Reproduce

1. Have a runner with the following config `runners_executor = "docker"`  and `runners_add_dind_volumes = true`
2. Launch the GitLab CI using the Runner.
3. Fail on the following step: `aws ecr get-login-password | docker login --username AWS --password-stdin aws.ecr.registry.url`

# Expected behavior

The runner and the spawned Docker instance is capable of running the necessary CI step to authenticate with AWS ECR and push image using the DIND config.

**Comment by kayman-mk** [comment]
Have you checked https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-gitlab-container-registry?

**Comment by SomaGallai** [comment]
@kayman-mk Yes and I have assumed that using `runners_add_dind_volumes = true` for the creation of the runner would contribute to the solution described as `Use Docker socket binding` explained in the documents. Only remaining work being for our side is using the the `service: docker-dind-specific-version` on the CI configuration of the job

**Comment by SomaGallai** [comment]
From the Runners perspective running `aws ecr get-login-password | docker login --username AWS --password-stdin aws.ecr.registry.url`
 fails with this error: `Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock`

 but running it as `aws ecr get-login-password | sudo docker login --username AWS --password-stdin aws.ecr.registry.url` results in successful login. 
So the issue was just bad permission on my end. But question that is closely related to this issue. 

When the CI tries to run this step: `aws ecr get-login-password | docker login --username AWS --password-stdin aws.ecr.registry.url` it gets the following error: 
```bash
An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn: aws:lam::ARN:user/ecr_pipeline is not authorized to perform: ecr:GetAuthorizationToken on resource: * because no identity-based policy allows the ecr:GetAuthorizationToken action
```

Even though the attached IAM to the ec2 instance running the Runner is allowed as the previously mentioned successful return code. Am I missing something?

**Comment by SomaGallai** [comment]
I have realised when the CI runs the docker instance it uses another User with another name compared to manually spawning the Docker image in the Runner which shares the same IAM Role as the Ec2 instance. Is there a way to enable having this logic of using the same IAM Role as the Runners instance inside the CI processes? @kayman-mk

**Comment by kayman-mk** [comment]
Never heard of this before. Could you please post the `.gitlab-ci.yml` and relevant parts of your Runner config?

**Comment by SomaGallai** [comment]
`.gitlab-ci.yml` relevant job config:
```yaml
build-and-push-AWS-ECR-docker-image:
  tags:
    - runner
  stage: package
  image:
    name: $CI_REGISTRY/$DOCKER_IMAGE_NAMESPACE/ecr-builder:latest
  services:
    - docker:23.0.3-dind
  dependencies:
    - build
  script:
    - /opt/asd/CreateDockerImage.sh
  only:
    - master
```

where `CreateDockerImage.sh` has the following config:
```bash
#!/bin/bash

##Create and push Docker image to AWS ECR
docker login registry.gitlab.com --username $gitlab_user --password $gitlab_password
docker build -t $DOCKER_REGISTRY/${CI_PROJECT_TITLE,,}:latest .
docker logout registry.gitlab.com
aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY
docker push $DOCKER_REGISTRY/${CI_PROJECT_TITLE,,}:latest

##Unassign env vars
unset AWS_SECRET_ACCESS_KEY
unset AWS_SECRET_KEY
unset AWS_SESSION_TOKEN
```

As mentioned before the Runner in CI fails at the script step of `aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY` 
with the following error: 
`An error occurred (AccessDeniedException) when calling the GetAuthorizationToken operation: User: arn: aws:lam::ARN:user/ecr_pipeline is not authorized to perform: ecr:GetAuthorizationToken on resource: * because no identity-based policy allows the ecr:GetAuthorizationToken action`

While Accessing the Runner and manually running the same docker image that is used in the CI process and running the steps in the script results with success. But when checking the AWS credentials using `aws sts get-caller-identity` I can see it uses the same Role as the Runners ec2 instance `arn:aws:sts::ARM:assumed-role/shared-gitlabrunner01-instance/i-instancenumber` in manually running everything while the CI uses an user called `ecr_pipeline ` I am not even sure where that name comes from.

Relevant Runner terraform config: 
```bash
module "runner" {
  source = "cattle-ops/gitlab-runner/aws"
  instance_type                     = local.gitlab-runner_instance_type
  aws_region                        = local.region
  environment                       = local.environment
  vpc_id                            = module.shared_vpc.vpc_id   
  subnet_id                         = module.shared_fra_gitlabrunner_subnets.id[0]
  runners_executor                  = "docker"
  runners_name                      = local.runner_name
  runners_gitlab_url                = local.gitlab_url
  enable_runner_ssm_access          = true
  userdata_pre_install              = "proxy setup here"
  runner_iam_policy_arns            = [ aws_iam_policy.aws_iam_policy_for_ecr.arn ]
  runners_add_dind_volumes          = true
  gitlab_runner_registration_config = {
    registration_token              = var.registration_token
    tag_list                        = "docker_runner"
    description                     = "runner default - auto"
    locked_to_project               = "true"
    run_untagged                    = "false"
    maximum_timeout                 = "3600"
  }
  tags                              = {  "sshname" = "gitlabrunner01", "Name" = "shared-gitlabrunner01" }
}
```

Hope this can be of help @kayman-mk

**Comment by kayman-mk** [comment]
Ah, interesting. Had this `ecr:AuthorizationToken` as well this week. The policy was missing for my executor. So could you please check which policies are attached to the role?

**Comment by SomaGallai** [comment]
The role `shared-gitlabrunner01-instance` has the following policies attached: 

- shared-gitlabrunner01-logging
- AmazonSSMManagedInstanceCore
- shared-gitlabrunner01-ssm
- shared-gitlabrunner01-session-manager
- shared-gitlabrunner01-service_linked_role
- policy_for_ecr_access (this one is attached by us in the terraform config previously showed)

The policy `policy_for_ecr_access ` has the following config:
```JSON
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "ecr:GetDownloadUrlForLayer",
                "ecr:BatchGetImage",
                "ecr:CompleteLayerUpload",
                "ecr:TagResource",
                "ecr:UploadLayerPart",
                "ecr:ListImages",
                "ecr:InitiateLayerUpload",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage"
            ],
            "Resource": [
                "arn:aws:ecr:region:ARN:repository/registry_name",
                "arn:aws:ecr:region:ARN:repository/registry_name"
            ]
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]
}
```

So by this config it should be working as expected and the manual process proves it working as well @kayman-mk

**Comment by SomaGallai** [comment]
Do you have any idea what could I try or change to make this work @kayman-mk ?

**Comment by kayman-mk** [comment]
@SomaGallai Have you verified this at runtime? Find the instance profile attached to your instance and then check the role?
Do you linked any permissions to the ECR itself?

Your ARN which was denied the access looks like a user ARN., but it should be the instance profile of the machine. Do you generate any access keys, ... somwhere in the pipeline? Maybe assume-role?

The other thing I noticed is, that we usually use `docker-machine`. Maybe we have a general problem with `docker` here.

**Comment by SomaGallai** [comment]
The issue was that in the organization where I work, AWS have a lot of accounts and one account where the login credentials came from had no access to the other accounts ECR. 
The weird user name came from that account as well. 
Switched back to `docker-machine` as well the only thing if the gitlab-ci uses `dind` image the terraform config should not have this line `runners_additional_volumes = ["/certs/client"]` as it gives error on the CI with conflicts as the `/certs/client` is already sharred
