### ISSUE TITLE
Custom Ingress Rules for Prometheus Port are not possible

### ISSUE THREAD

**Issue by MrGiga** [cattle-ops/terraform-aws-gitlab-runner#785]
# Describe the bug

Configuration for a Prometheus listening port is possible but there seems to be no way to set a custom ingress rule to allow outside resources to access that port. Let me know if I am overlooking something.

# To Reproduce

1. Set prometheus_listen_address to valid_ip:port
2. Try to access valid_ip:port

# Expected behavior

Port should be accessible from outside resource or there should be a way to set custom ingress rules.

# Additional context

**Comment by MrGiga** [comment]
I believe i may be incorrect on this one, I wasn't sure if prometheus ran on the docker+machine or the runner instance. I am verifying now

**Comment by MrGiga** [comment]
Closing due to my own misunderstanding. 

Prometheus metrics are off of the docker+machine and not the runner instances themselves.

**Comment by lefterisALEX** [comment]
hi, was looking for an answer about same thing and bumped on your issue.
I see prometheus is listening on the runner agent if i include the following configuration:

```
    runner_manager = {
      gitlab_check_interval = 3 
      maximum_concurrent_jobs = 10 
      prometheus_listen_address = "[::]:8093" 
  }
```

I can access that endpoint only if i allow ingress for port 8093 on the security group which is attached on the runner agent. How did you get the metrics?

**Comment by MrGiga** [comment]
I unfortunately won’t be much help on this one because this is from a year ago which was prior to the current total rewrite of parameter names and organization. We did not end up using the Prometheus metrics
