### ISSUE TITLE
Unable to create Spot Fleet request

### ISSUE THREAD

**Issue by iulian-balan** [cattle-ops/terraform-aws-gitlab-runner#830]
Using the latest version I am not able to correctly verify that I am using spot fleet. In the EC2 Spot requests I am seeing an instance request instead of a fleet. Additionally, there's no fleet available when using `aws ec2 describe-fleets`.

# To Reproduce

1. Create a default project as shown in the examples
2. Modify the runner to contain the configuration used in https://github.com/cattle-ops/terraform-aws-gitlab-runner#scenario-use-of-spot-fleet
3. `terraform apply`
4. Trigger a new run
5. Observe the Spot Requests in the AWS console is of type `instance`

# Expected behavior
In the EC2 Spot requests I am seeing an instance request instead of a `fleet`.

# Additional context

```
module "runner2" {
  source  = "cattle-ops/gitlab-runner/aws"
  version = "6.4.0"

  aws_region  = "us-west-2"
  environment = "spot-runners"

  vpc_id                    = module.vpc.vpc_id
  subnet_id                 = module.vpc.private_subnets[0] # subnet of the agent
  fleet_executor_subnet_ids = module.vpc.private_subnets

  docker_machine_instance_types_fleet = ["t3a.medium", "t3.medium", "t2.medium"]
  use_fleet                           = true

  runners_name       = "docker-machine-test-iulian"
  runners_gitlab_url = "https://gitlab.com"

  gitlab_runner_registration_config = {
    registration_token = var.registration_token
    tag_list           = "iulian-test"
    description        = "runner default"
    locked_to_project  = "true"
    run_untagged       = "false"
    maximum_timeout    = "3600"
  }
}
```

**EDIT**: updated missing command in the first paragraph.

**Comment by kayman-mk** [comment]
Just tried this feature during the update to 6.4.0

I do not see any fleets. `aws ec2 describe-fleets` returns an empty array. But the module works as expected. Jobs are still being processed.

I do not see any errors in the agent's log. `config.toml` looks good and enables `amazonec2-use-fleet`.

My agent runs in `eu-central-1a`. I activated all 3 AZs for the workers and used multiple instances types. The created machine lives in `eu-central-1c` and the 3rd machine type was selected from the array.

So I think everything works as expected. Any other thoughts on that?

**Comment by iulian-balan** [comment]
According to the documentation https://gitlab.com/cki-project/docker-machine/-/blob/v0.16.2-gitlab.19-cki.2/docs/drivers/aws.md#fleet-mode: 

> With `--amazonec2-use-fleet`, Instances are requested via the `CreateFleet` API call.

I have the same experience as you have, meaning that the module doesn't return any error and the `config.toml` seems to contain what is needed for this to trigger a fleet request. 

My next question would be: is this a bug in the docker+machine fork or maybe we are not using the correct version? I must admit that I don't quite understand where you specify that in your code.

**Comment by Kadeux** [comment]
Yes, according to the documentation, docker-machine use `CreateFleet` API calls, but it's normal to see that there is no SpotFleet requests in the spot demands since docker-machine spot fleets requests type is `instant`.

Thus, you will see a basic spot instance request in the UI but it is actually a spot fleet request. You can check in CloudTrail the API calls from the runner ans you will see that the runner is calling `CreateFleet`

**Comment by kayman-mk** [comment]
Thank for shed some light on this, @Kadeux Wasn't aware of the details but have seen what you wrote.
