### ISSUE TITLE
Shared cache for multiple runners

### ISSUE THREAD

**Issue by bernhardbirkner** [cattle-ops/terraform-aws-gitlab-runner#839]
Hi Everyone,
thanks for the awesome module that makes it super easy to setup gitlab-runners.

# Describe the solution you'd like
In my project I am using multiple runners (1 docker+machine and 2 docker). Right now each runner uses their own S3 buckets to store the cache - so the runner shares the cache across its own jobs, but cache is not shared between runners. Is there any plan to enable sharing the S3 cache across multiple instances of the same module?

# Describe alternatives you've considered

# Suggest a solution

Add an S3 resource or other storage resource as input to the module which can be used for multiple instances of that gitlab-runner module.

**Comment by kayman-mk** [comment]
Yeah, this is already possible:

```hcl
module "cache" {
  source  = "cattle-ops/gitlab-runner/aws//modules/cache"
  version = "6.4.0"

  cache_expiration_days  = 7
  cache_lifecycle_prefix = "" # module default is wrong

  environment = var.environment
  tags        = local.tags
}

module "gitlab_runner_uncritical_1" {
  for_each = data.aws_subnet.runners

  source  = "cattle-ops/gitlab-runner/aws"
  version = "6.4.0"

  # ...

  cache_shared = true

  cache_bucket = {
    create = false
    policy = "${module.cache.policy_arn}"
    bucket = "${module.cache.bucket}"
  }
}

module "gitlab_runner_uncritical_2" {
  for_each = data.aws_subnet.runners

  source  = "cattle-ops/gitlab-runner/aws"
  version = "6.4.0"

  # ...

  cache_shared = true

  cache_bucket = {
    create = false
    policy = "${module.cache.policy_arn}"
    bucket = "${module.cache.bucket}"
  }
}
```

There is also one [example](https://github.com/cattle-ops/terraform-aws-gitlab-runner/blob/main/examples/runner-public/main.tf) in the repository:

**Comment by bernhardbirkner** [comment]
Oh wow, great work!
I think it can be closed then :)
Thanks for the help!
