### ISSUE TITLE
Support MaxGrowthRate

### ISSUE THREAD

**Issue by dsalaza4** [cattle-ops/terraform-aws-gitlab-runner#851]
# Describe the solution you'd like

The module already supports parameters like idleCount.

Maybe it should also support MaxGrowthRate: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersmachine-section

**Comment by kayman-mk** [comment]
Valid point. Version 7 adds many parameters. Guess we should add `MaxGrowthRate` to #723

**Comment by dsalaza4** [comment]
Looking forward to this! 

I'm currently trying a completely on demand approach (idle-count = 0) but runners tend to leave orphaned workers.

I think it is because they run out of memory when very high workloads reach them in a very short amount of time (From 0 to 300 jobs leaves some orphaned machines for a 8GB memory runner).
