### ISSUE TITLE
"key_pair_name" is not expected here

### ISSUE THREAD

**Issue by barrynorman** [cattle-ops/terraform-aws-gitlab-runner#877]
# Describe the bug

I copied the spot fleet exmaple from here: https://github.com/cattle-ops/terraform-aws-gitlab-runner#scenario-use-of-spot-fleet but I get this error.

```
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 94, in module "runner":
│   94:   key_pair_name                             = var.environment + "_KEY"
│ 
│ An argument named "key_pair_name" is not expected here.
╵
```

# To Reproduce

1. Use this configuration: https://github.com/cattle-ops/terraform-aws-gitlab-runner#scenario-use-of-spot-fleet
3. See error

# Expected behavior

Configuration Examples should work.

# Additional context

I guess it was renamed to "fleet_key_pair_name" but not sure.

**Comment by Kadeux** [comment]
Hello, you are right I forgot to update the configuration example. Thank you
