### ISSUE TITLE
Unable to communicate with AWS APIs due to security group restrictions when VPC endpoints are enabled with gitlab_runner module

### ISSUE THREAD

**Issue by karthikholla** [cattle-ops/terraform-aws-gitlab-runner#920]
**version** 
"6.5.1"

**Issue Description:**
When VPC endpoints are enabled within our infrastructure and using the gitlab_runner module, our pipeline encounters communication issues with AWS APIs. The problem seems to be caused by automatically assigned security groups, which prevent the pipeline from accessing the required AWS services.

Upon investigation, we discovered that adding an Ingress rule to the security group, allowing all traffic (i.e., a self-referencing security group rule), resolves the communication problem, and the pipeline can successfully talk to the AWS APIs.

However, relying on this manual workaround is not ideal and might introduce security risks. To ensure a more robust and secure setup, we aim to configure the gitlab_runner module to handle this situation properly when VPC endpoints are enabled.

<img width="767" alt="image" src="https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/19381923/12f1d8b3-27c2-4e32-8dd9-324e5578719f">

**Expected Behavior:**
The gitlab_runner module should be able to automatically handle the necessary security group configurations when VPC endpoints are enabled, allowing the pipeline to communicate with AWS APIs seamlessly without requiring manual modifications.

**Steps to Reproduce:**

1. Enable VPC endpoints in the AWS infrastructure.
2. Use the gitlab_runner module to run pipelines that interact with AWS APIs.
3. Observe the communication failure with AWS APIs due to security group restrictions.

**Current Workaround:**
Manually add an Ingress rule to the security group, allowing all traffic (self-referencing security group rule).
<img width="609" alt="image" src="https://github.com/cattle-ops/terraform-aws-gitlab-runner/assets/19381923/383d39e2-b8cb-40d9-a334-310d5801894d">

**Comment by kayman-mk** [comment]
The preferred way is `var.gitlab_runner_egress_rules` or `var.docker_machine_egress_rules` (depending on the type of runner you use) to configure the outbound rules. The tricky part is to determine the IP addresses for your whitelist. I haven't found a good solution so far. What I tried in another project was parsing the `https://ip-ranges.amazonaws.com/ip-ranges.json` list of CIDRs. Still working without problems so far. But the CIDR list gets really long, ...

Another option I thought of was to analyze the managed prefix lists which are automatically created upon VPC endpoint creation. This would be the best option from my point of view. But I never finished this.

Detecting the exact setup of your network infrastructure is out of scope here.

**Comment by kayman-mk** [comment]
Just had a quick look how to parse the prefix lists. Seems to be easy:

1. Find the correct list with `aws ec2 describe-managed-prefix-lists`. Use the `PrefixListName` attribute to find the correct list.
2. Get the CIDRs: `aws ec2 describe-prefix-lists --prefix-list-ids pl-a3a144ca`. Prefix list id is the `PrefixListId` attribute from the output of the command above.

**Comment by karthikholla** [comment]
@kayman-mk 
```
  gitlab_runner_egress_rules = var.enable_vpc_endpoint ? [
    {
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
      prefix_list_ids  = [data.aws_prefix_list.gateway_vpc_endpoint_prefix_list_id[0].id]
      from_port        = 0
      protocol         = "-1"
      security_groups  = null
      self             = null
      to_port          = 0
      description      = null
    }
  ] : []

  docker_machine_egress_rules = var.enable_vpc_endpoint ? [
    {
      cidr_blocks      = ["0.0.0.0/0"]
      ipv6_cidr_blocks = ["::/0"]
      prefix_list_ids  = [data.aws_prefix_list.gateway_vpc_endpoint_prefix_list_id[0].id]
      from_port        = 0
      protocol         = "-1"
      security_groups  = null
      self             = null
      to_port          = 0
      description      = null
    }
  ] : []
```

I do already have the following configuration in the module configured, 
But, the blocker here is `ingress`.
Allowing all traffic (self-referencing security group rule) as an ingress rule. There is no parameter to modify/add the ingress rules to the `docker_machine` security group rules.

**Comment by kayman-mk** [comment]
Oh yes, that looks better. Wasn't aware of the `prefix_list_ids` option.

Not sure if I understand everything. But using VPC endpoints shouldn't require ingress rules as your machine is connecting to the endpoint (thus an egress rule is needed). Who initiate a connection to your machine? There shouldn't be any ingress rules needed.
