### ISSUE TITLE
Add module.cache.policy_arn to outputs for other gitlab runner module to reference

### ISSUE THREAD

**Issue by houdinisparks** [cattle-ops/terraform-aws-gitlab-runner#943]
# Describe the solution you'd like

I have multiple runners deployed, in a _docker-machine runner - multiple runner agents_ architecture.
I want to re-use the cache bucket (of a runner) created, with other runners, but currently there's no easy way yet to reference the docker-machine policy arn created within the `module.cache` child module. 
# Describe alternatives you've considered

# Suggest a solution

Proposing to

1. Add `module.cache.policy_arn` as an output to _outputs.tf_ file, i.e

```hcl
output "runner_cache_bucket_users_policy_arn" {
  description = "ARN of the policy for users of the cache (bucket)."
  value       = length(module.cache) > 0 ? module.cache[0].policy_arn : null
}
```

# Additional context

**Comment by kayman-mk** [comment]
@houdinisparks Have you had the time to check this?
