### ISSUE TITLE
aws_ssm_parameter has hard coded name which prevents from generating multiple runners

### ISSUE THREAD

**Issue by lmilbaum** [cattle-ops/terraform-aws-gitlab-runner#967]
# Describe the bug

My configuration consists of two runners.  Each attached to its own repository.
When the second runner is applied, the creation of `aws_ssm_parameter` resource from main.tf line 14 fails because 
resource with the same name exists.

# To Reproduce

Configure two module blocks in the configuration

# Expected behavior

Ability to define the resource name dynamically such that the second runner creates `aws_ssm_parameter` resource with a different name

# Additional context

**Comment by kayman-mk** [comment]
I guess the `environment` is identical which shouldn't. Could you please set different environment names for different runners?

**Comment by lmilbaum** [comment]
> I guess the `environment` is identical which shouldn't. Could you please set different environment names for different runners?

I could but then I need to remember that when the code changes to apply it to two production environments. Not ideal.

**Comment by kayman-mk** [comment]
Could you please elaborate on this? I didn't get the point.

```hcl
module "gitlab_runner_1" {
  environment= "abc"
}

module "gitlab_runner_2" {
  environment= "def"
}
```

I don't have to do anything in case the module changes. Just two runners with two different environment names. The runner token which is stored, is totally managed by the module. There is no need to adjust something.

**Comment by lmilbaum** [comment]
> Could you please elaborate on this? I didn't get the point.
> 
> ```terraform
> module "gitlab_runner_1" {
>   environment= "abc"
> }
> 
> module "gitlab_runner_2" {
>   environment= "def"
> }
> ```
> 
> I don't have to do anything in case the module changes. Just two runners with two different environment names. The runner token which is stored, is totally managed by the module. There is no need to adjust something.

Thanks for the clarification. My misunderstanding. Will try the suggested solution.
